Don't panic immediately when encountering an argument parsing error
insou22/mipsy pull request #127
Opened 2021-12-28 11:15 UTC by joooooooooooooooooooooooooooooooooooosh

This is a very straightforward patch which fixes the class of argument parsing errors in #118.
Previous behaviour:
```
[mipsy] load test_files/success/add.s
success: file loaded

[mipsy] step

_start:
0x80000000 kernel [0x3c1a0040]    lui    $k0, 64
[mipsy] print @all
ERROR: Parsing Error: Error { input: LocatedSpan { offset: 0, line: 1, fragment: [64, 97, 108, 108], extra: () }, code: Char }
thread 'main' panicked at 'this should never happen - please report an issue at https://github.com/insou22/mipsy', /home/joshh/Documents/code/mipsy/crates/mipsy_parser/src/misc.rs:51:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

New behaviour:
```
[mipsy] load test_files/success/add.s
success: file loaded

[mipsy] step

_start:
0x80000000 kernel [0x3c1a0040]    lui    $k0, 64
[mipsy] print @all
error: bad argument `@all` for <item>
tip: try `help print`

[mipsy] 
```

Upgrading rustyline is not strictly needed for this patch but was just the result of some work done earlier while attempting to overload the C-f readline binding. However upgrading to the new rustyline version shouldn't cause any issues.

2021-12-29 06:23 UTC, insou22 requested changes
Left a couple comments -- let me know if they're something you're happy to fix up, otherwise I'm happy to make the changes myself if you don't have the time etc.

2021-12-29 06:23 UTC, insou22 commented on crates/mipsy_interactive/src/interactive/mod.rs
> +    use {KeyCode as K, KeyEvent as E, Modifiers as M};
nit: I think I'd prefer this as `use {KeyCode::{Left, Right}, Modifers::CTRL};` and simply using the whole `KeyEvent` variant name.

2021-12-29 06:23 UTC, insou22 commented on crates/mipsy_parser/src/misc.rs
> +fn parse_multispace<T>(i: nom_locate::LocatedSpan<&[u8]>, file_name: Option<Rc<str>>) -> Result<T, ErrorLocation> {
maybe `fn leftover_tokens_strip_multispace` or something?
also, no need to type `nom_locate::LocatedSpan<&[u8]>`, we have the type alias `Span<'a>`, you'll just have to make the `fn` generic over `'a` (which is already what is happening with lifetime elision) -- so something like `fn leftover_tokens_strip_multispace<'a>(i: Span<'a>, ...) ...`

It also is a bit confusing to return a `forall T. Result<T, ErrorLocation>`, given it only returns the `Err` variant -- this is only compiling due to the compiler being clever, similar to never type (`!`) promotion. I would just return the `ErrorLocation`, and then wrap that in `Err(...)` at the call sites in the `parse_result` function

2021-12-29 06:31 UTC, joooooooooooooooooooooooooooooooooooosh commented
> Left a couple comments -- let me know if they're something you're happy to fix up, otherwise I'm happy to make the changes myself if you don't have the time etc.

No worries, i'll fix them up

2021-12-31 04:27 UTC, insou22 approved these changes
LGTM!

2021-12-31 04:27 UTC, merged