Add labels to mipsy_web data view
insou22/mipsy pull request #267
Opened 2022-10-21 13:04 UTC by Dylan-Brotherston

2022-10-21 13:36 UTC, joooooooooooooooooooooooooooooooooooosh commented
doesn't need to be in this PR but adding a button somewhere to toggle the labels showing in the rendered data segment itself rather than just hovering on tooltip would be nice

2022-10-21 13:40 UTC, joooooooooooooooooooooooooooooooooooosh approved these changes

2022-10-22 01:00 UTC, joooooooooooooooooooooooooooooooooooosh requested changes

2022-10-22 01:00 UTC, joooooooooooooooooooooooooooooooooooosh commented on crates/mipsy_lib/src/inst/register.rs
> +    Register::Fp,
I would rather this be left in the more compact (and organised) original form, you can add `#[rustfmt::skip]` to line 41 to preserve the formatting when running `rustfmt` on everything else

2022-10-22 01:00 UTC, joooooooooooooooooooooooooooooooooooosh commented on crates/mipsy_lib/src/inst/register.rs
> +            Self::Ra => 31,
same here

2022-10-22 01:00 UTC, joooooooooooooooooooooooooooooooooooosh commented on crates/mipsy_lib/src/inst/register.rs
> +            9 => Ok(Self::T1),
and here (the new formatting for `_` case is fine)

2022-10-22 01:00 UTC, joooooooooooooooooooooooooooooooooooosh commented on crates/mipsy_lib/src/inst/register.rs
> +            Self::Ra => "RA",
here

2022-10-22 01:00 UTC, joooooooooooooooooooooooooooooooooooosh commented on crates/mipsy_lib/src/inst/register.rs
> +            Self::Ra => "ra",
here

2022-10-22 01:00 UTC, joooooooooooooooooooooooooooooooooooosh commented on crates/mipsy_web/src/components/data_segment.rs
> +                        let mut style = String::new();
style could still be initialised as `String::from("border: 2px solid ");` but that's up to you

2022-10-22 22:42 UTC, joooooooooooooooooooooooooooooooooooosh approved these changes

2022-10-22 22:47 UTC, merged

2022-10-24 05:33 UTC, Dylan-Brotherston commented
This has a massive performance overhead and might want to be rolled back and rethought.

2022-10-24 06:27 UTC, joooooooooooooooooooooooooooooooooooosh commented
wait really? can you give examples of where this is noticeable? The only thing added I can see that could have a noticeable perf impact is the label iteration on every byte, but this could be rethought easily by creating a HashMap once before the loops start

2022-10-24 06:59 UTC, Dylan-Brotherston commented
It's hard to do an exact benchmark. 
But it is noticeably slower.

If you are actively viewing the data tab it is extremely obvious it has slowed down.

2022-10-24 07:20 UTC, joooooooooooooooooooooooooooooooooooosh commented
I'm not noticing anything? Stepping through commands that modify the data tab and/or position of $sp/$fp affect the data tab instantaneously and even running two_powerful to completion updates without issue.